name: ci

on: [push, pull_request]

jobs:
  build:
    name: tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.6.0
      
      - name: Check fmt
        if: matrix.os == 'ubuntu-latest'
        run: deno fmt --check
      
      - name: Test
        if: matrix.os == 'ubuntu-latest'
        run:  deno test -A
      
      - name: Test example
        if: matrix.os == 'ubuntu-latest'
        run: |
          deno run -A ./examples/router.ts &
          sleep 10
          kill $!
